language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - REPORTLAB=2.6
  - REPORTLAB=2.7
  - REPORTLAB=3.0
  - REPORTLAB=3.1.44
  - REPORTLAB=3.2

matrix:
  exclude:
    - env: REPORTLAB=3.1.44
      python: "2.6"
    - env: REPORTLAB=3.2.0
      python: "2.6"
    - env: REPORTLAB=2.6
      python: "3.3"
    - env: REPORTLAB=2.6
      python: "3.4"
    - env: REPORTLAB=2.7
      python: "3.3"
    - env: REPORTLAB=2.7
      python: "3.4"

install:
  - pip install reportlab==$REPORTLAB
  - python setup.py install

script: python setup.py test
